In [1]:
import pandas as pd
df = pd.read_excel('../data/creditrisk.xlsx')
print(df.shape)
df.head()

(32581, 29)

,client_ID,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,...,city_latitude,city_longitude,employment_type,loan_term_months,loan_to_income_ratio,other_debt,debt_to_income_ratio,open_accounts,credit_utilization_ratio,past_delinquencies
0,CUST_00001,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,...,43.6532,-79.3832,Self-employed,36,0.593220,8402.453850,0.735635,14,0.495557,0
1,CUST_00002,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,...,43.6532,-79.3832,Full-time,36,0.104167,1607.802794,0.271646,10,0.585436,3
2,CUST_00003,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,...,51.6214,-3.9436,Full-time,36,0.572917,2760.505633,0.860469,14,0.750732,0
3,CUST_00004,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,...,49.2827,-123.1207,Part-time,12,0.534351,7155.286150,0.643592,15,0.379333,0
4,CUST_00005,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,...,42.8864,-78.8784,Part-time,36,0.643382,15626.153439,0.930628,4,0.228103,0

In [2]:
print(df.columns.tolist())

['client_ID', 'person_age', 'person_income', 'person_home_ownership', 'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt', 'loan_int_rate', 'loan_status', 'loan_percent_income', 'cb_person_default_on_file', 'cb_person_cred_hist_length', 'gender', 'marital_status', 'education_level', 'country', 'state', 'city', 'city_latitude', 'city_longitude', 'employment_type', 'loan_term_months', 'loan_to_income_ratio', 'other_debt', 'debt_to_income_ratio', 'open_accounts', 'credit_utilization_ratio', 'past_delinquencies']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   client_ID                   32581 non-null  object
 1   person_age                  32581 non-null  int64
 2   person_income               32581 non-null  int64
 3   person_home_ownership       32581 non-null  object
 4   person_emp_length           31686 non-null  float64
 5   loan_intent                 32581 non-null  object
 6   loan_grade                  32581 non-null  object
 7   loan_amnt                   32581 non-null  int64
 8   loan_int_rate               29465 non-null  float64
 9   loan_status                 32581 non-null  int64
 10  loan_percent_income         32581 non-null  float64
 11  cb_person_default_on_file   32581 non-null  object
 12  cb_person_cred_hist_length  32581 non-null  int64
 13  gender                      32581 non-null  object
 14  marital_status              32581 non-null  object
 15  education_level             32581 non-null  object
 16  country                     32581 non-null  object
 17  state                       32581 non-null  object
 18  city                        32581 non-null  object
 19  city_latitude               32581 non-null  float64
 20  city_longitude              32581 non-null  float64
 21  employment_type             32581 non-null  object
 22  loan_term_months            32581 non-null  int64
 23  loan_to_income_ratio        32581 non-null  float64
 24  other_debt                  32581 non-null  float64
 25  debt_to_income_ratio        32581 non-null  float64
 26  open_accounts               32581 non-null  int64
 27  credit_utilization_ratio    32581 non-null  float64
 28  past_delinquencies          32581 non-null  int64
dtypes: float64(9), int64(8), object(12)
memory usage: 7.2+ MB

In [4]:
df.isnull().sum()

client_ID                        0
person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
gender                           0
marital_status                   0
education_level                  0
country                          0
state                            0
city                             0
city_latitude                    0
city_longitude                   0
employment_type                  0
loan_term_months                 0
loan_to_income_ratio             0
other_debt                       0
debt_to_income_ratio             0
open_accounts                    0
credit_utilization_ratio         0
past_delinquencies               0
dtype: int64

In [5]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length,city_latitude,city_longitude,loan_term_months,loan_to_income_ratio,other_debt,debt_to_income_ratio,open_accounts,credit_utilization_ratio,past_delinquencies
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000,32581.000000,32581.000000,32581.000000,32581.000000,3.258100e+04,32581.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211,45.407613,-63.805473,38.501581,0.170553,1.156796e+04,0.345208,8.042018,0.499884,0.505141
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001,7.644809,46.615580,16.012441,0.107049,1.306093e+04,0.129406,4.328087,0.259530,0.711745
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000,29.760400,-123.365600,12.000000,0.000789,2.252074e+02,0.064502,0.000000,0.050001,0.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000,40.712800,-96.797000,24.000000,0.089655,5.387168e+03,0.251236,4.000000,0.275358,0.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000,46.813900,-75.697200,36.000000,0.148148,8.995071e+03,0.333188,8.000000,0.500289,0.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000,51.507400,-3.943600,60.000000,0.229167,1.456293e+04,0.423142,12.000000,0.725056,1.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000,55.953300,-0.127800,60.000000,0.830000,1.187999e+06,1.053888,15.000000,0.949998,6.000000

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['loan_status'].value_counts()
df['loan_status'].value_counts(normalize=True)  # tỷ lệ %

loan_status
0    0.781836
1    0.218164
Name: proportion, dtype: float64

In [8]:
df[['person_age', 'person_emp_length', 'person_income']].describe()

         person_age  person_emp_length  person_income
count  32581.000000       31686.000000   3.258100e+04
mean      27.734600           4.789686   6.607485e+04
std        6.348078           4.142630   6.198312e+04
min       20.000000           0.000000   4.000000e+03
25%       23.000000           2.000000   3.850000e+04
50%       26.000000           4.000000   5.500000e+04
75%       30.000000           7.000000   7.920000e+04
max      144.000000         123.000000   6.000000e+06

In [9]:
for col in ['loan_grade', 'loan_intent', 'person_home_ownership', 'cb_person_default_on_file']:
    print(col, ':', df[col].unique())

loan_grade : ['D' 'B' 'C' 'A' 'E' 'F' 'G']
loan_intent : ['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
person_home_ownership : ['RENT' 'OWN' 'MORTGAGE' 'OTHER']
cb_person_default_on_file : ['Y' 'N']

In [10]:
# 1. Outlier person_age (max 144 - vô lý)
df = df[df['person_age'] <= 100]

In [11]:
# 2. Outlier person_emp_length (max 123 - vô lý, ko thể làm 123 năm)
df = df[df['person_emp_length'] <= 60]

In [12]:
# 3. Fill missing person_emp_length bằng median
df['person_emp_length'] = df['person_emp_length'].fillna(df['person_emp_length'].median())

# 4. Fill missing loan_int_rate theo median của từng loan_grade (lãi suất phụ thuộc grade)
df['loan_int_rate'] = df.groupby('loan_grade')['loan_int_rate'].transform(
    lambda x: x.fillna(x.median())
)

In [13]:
# Kiểm tra lại
print(df.isnull().sum().sum())  # phải = 0
print(df.shape)

0
(31679, 29)

In [ ]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:your_password_here@localhost:5432/credit_risk_db')

df.to_sql('loans', engine, if_exists='replace', index=False)
print("Done!")

Done!